/*
 * @Author: xiongman
 * @Date: 2023-10-25 16:15:33
 * @LastEditors: chenmeifeng
 * @LastEditTime: 2025-06-13 11:07:22
 * @Description:
 */

import { ThemeConfig } from "antd"

export const AntdThemeData: ThemeConfig = {
  hashed: true,
  token: {
    colorText: "var(--fontcolor)",
    colorPrimary: "var(--primary-color)",
    colorWarning: "var(--warning-color)",
    colorInfo: "var(--white-color)",
    colorBgLayout: "var(--bgcolor)",
    colorTextPlaceholder: "var(--graycolor)",
    colorBgElevated: "var(--menu-bg)",
    borderRadius: 0,
    borderRadiusOuter: 0,
    borderRadiusSM: 0,
    fontFamily:
      '"FZYouHei", sans-serif',
  },
  components: {
    Modal: {
      padding: 8,
      paddingMD: 10,
      paddingContentHorizontalLG: 16,
      colorText: "var(--fontcolor)",
      contentBg: "transparent",
      headerBg: "transparent",
      colorIcon: "var(--deep-gray)",
      titleColor: "var(--deep-font-color)",
    },
    Steps: {
      colorPrimary: "var(--split-color)",
      colorSplit: "var(--split-color)",
      colorText: "var(--success-color)",
      colorTextDisabled: "var(--deep-font-color)",
      colorTextDescription: "var(--deep-font-color)",
      colorTextLabel: "var(--fontcolor)",
      colorFillContent: "var(--split-color)",
      colorTextLightSolid: "var(--deep-font-color)",
      colorBgContainer: "var(--bg-hover)",
    },
    Spin: { colorPrimary: "var(--error-color)" },
    Notification: {
      colorBgElevated: "var(--table-hover-color)",
      colorIcon: "var(--deep-gray)",
      colorIconHover: "var(--graycolor)",
      colorInfo: "var(--white-color)",
      colorText: "var(--fontcolor)",
      colorTextHeading: "var(--fontcolor)",
    },
    Popover: {
      colorBgElevated: "var(--primary-color)",
      controlItemBgHover: "var(--bg-active)",
      colorText: "var(--fontcolor)",
    },
    Tabs: {
      borderRadiusLG: 0,
      colorBorderBg: "transparent",
      colorBorderSecondary: "var(--split-color)",
      itemHoverColor: "var(--fontcolor)",
      itemSelectedColor: "var(--fontcolor)",
      cardBg: "transparent",
      colorBgContainer: "transparent",
      controlHeightLG: 32,
      controlHeight: 32,
      horizontalMargin: "0",
      horizontalItemMarginRTL: "0",
    },
    Card: {
      controlHeight: 100,
      borderRadiusLG: 4,
      colorBgContainer: "transparent",
      colorTextHeading: "var(--fontcolor)",
    },
    Table: {
      cellPaddingInlineSM: 4,
      paddingSM: 4,
      padding: 6,
      paddingContentVerticalLG: 10,
      borderRadius: 0,
      borderRadiusLG: 0,
      headerBg: "var(--table-head-color)",
      headerColor: "var(--white-color)",
      rowHoverBg: "rgba(63,123,250,0.2)",
      rowSelectedBg: "rgba(63,123,250,0.2)",
      colorSplit: "var(--white-color)",
      colorFillAlter: "var(--fill-color)",
      colorIcon: "var(--graycolor)",
      colorIconHover: "var(--deep-gray)",
      colorText: "var(--fontcolor)",
      colorBgContainer: "var(--bgcolor)",
      colorBorderSecondary: "transparent",
      colorTextHeading: "var(--fontcolor)",
    },
    Pagination: {
      itemActiveBg: "transparent",
      colorPrimaryBorder: "transparent",
      colorPrimary: "var(--fontcolor)",
      colorPrimaryHover: "var(--deep-font-color)",
      itemInputBg: "transparent",
    },
    Progress: { margin: 0, marginXS: 0 },
    Menu: {
      subMenuItemBorderRadius: 0,
      colorBgContainer: "var(--menu-bg)",
      itemColor: "var(--white-color)",
      itemActiveBg: "var(--menu-item-bg)",
      // itemBg: "var(--menu-item-bg)",
      itemHoverBg: "var(--graycolor)",
      itemSelectedColor: "var(--fontcolor)",
      itemSelectedBg: "var(--white-color)",
      itemHoverColor: "var(--fill-color)",
      itemBorderRadius: 10,
      itemMarginBlock: 6,
      itemMarginInline: 6,
      popupBg: "var(--menu-item-bg)",
      horizontalItemSelectedColor: "var(--fill-color)",
    },
    Dropdown: {
      colorBgElevated: "#a4c7ff",
    },
    InputNumber: {
      activeBg: "var(--input-bg)",
      colorPrimary: "var(--input-bg)",
      colorPrimaryHover: "var(--light-primary)",
      colorBgContainer: "var(--input-bg)",
      colorBorder: "var(--border-color)",
      colorWarning: "var(--alarm)",
      colorWarningBorder: "var(--alarm)",
      colorWarningBorderHover: "var(--alarm)",
      handleBg: "var(--bg-active)",
      hoverBorderColor: "var(--primary-color)",
      colorIconHover: "var(--deep-gray)",
      colorBgContainerDisabled: "var(--input-bg)",
    },
    Input: {
      colorPrimary: "var(--input-bg)",
      colorPrimaryHover: "var(--light-primary)",
      colorBgContainer: "var(--input-bg)",
      colorBorder: "var(--border-color)",
      controlOutline: "var(--border-color)",
      colorIconHover: "var(--deep-gray)",
      colorTextQuaternary: "var(--deep-gray)",
      colorTextTertiary: "var(--graycolor)",
    },
    Select: {
      colorTextQuaternary: "var(--white-color)",
      colorText: "var(--fontcolor)",
      colorBgElevated: "var(--white-color)",
      controlItemBgHover: "var(--bg-active)",
      controlItemBgActiveHover: "var(--bg-hover)",
      controlItemBgActive: "var(--bg-active)",
      colorBgContainer: "var(--input-bg)",
      colorBorder: "var(--border-color)",
      colorPrimaryHover: "var(--border-color)",
    },
    Tree: {
      colorBgContainer: "var(--bg-hover)",
      colorBgContainerDisabled: "var(--graycolor)",
      colorBorder: "var(--bg-active)",
      colorPrimary: "var(--bg-active)",
      colorPrimaryHover: "var(--bg-hover)",
    },
    TreeSelect: {
      colorBgContainerDisabled: "var(--graycolor)",
      colorBgElevated: "var(--primary-color)",
      colorText: "var(--fontcolor)",
      colorBorder: "transparent",
      colorTextDisabled: "var(--fontcolor)",
    },
    Checkbox: {
      colorBorder: "var(--bg-hover)",
      colorBgContainer: "var(--input-bg)",
      colorBgContainerDisabled: "var(--graycolor)",
      controlItemBgHover: "var(--bg-active)",
      controlItemBgActive: "var(--bg-active)",
    },
    Switch: {
      colorPrimary: "var(--alarm)",
      colorPrimaryHover: "var(--alarm)",
      handleBg: "var(--border-color)",
    },
    DatePicker: {
      borderRadius: 0,
      borderRadiusOuter: 0,
      borderRadiusSM: 0,
      colorText: "var(--fontcolor)",
      colorBgElevated: "var(--primary-color)",
      controlItemBgHover: "var(--bg-active)",
      controlItemBgActiveHover: "var(--bg-hover)",
      colorLink: "var(--graycolor)",
      colorLinkActive: "var(--white-color)",
      colorPrimary: "var(--split-color)",
      colorBgContainer: "var(--input-bg)",
      colorBorder: "var(--border-color)",
      colorSplit: "var(--deep-gray)",
      colorTextDisabled: "var(--deep-gray)",
    },
    Button: {
      borderRadius: 2,
      borderRadiusSM: 2,
      colorText: "var(--fontcolor)",
      colorPrimaryHover: "var(--deep-gray)",
      colorTextDisabled: "var(--graycolor)",
    },
    Empty: {
      colorText: "var(--graycolor)",
      colorTextDisabled: "var(--graycolor)",
    },
  },
}
