export default {
  WT: [
    {
      label: "测试模板1",
      value: "1",
      pointName: "MState",
      formula: [
  { "priority": 1, "rule": "Turstatus in (8)||(ConGridsideVoltageL1L2@1m@MAX-ConGridsideVoltageL1L2@1m@MIN==0 && WindSpeed1@1m@MAX-WindSpeed1@1m@MIN==0)", "ruleBefore": "", "duration": 0, "mainStateCode": 7, "mainStateName": "通讯中断" },
  { "priority": 1, "rule": "WindSpeed1@1m@AVG==null", "ruleBefore": "", "duration": 0, "mainStateCode": 7, "mainStateName": "通讯中断" },
  { "priority": 2, "rule": "Turstatus in (5) ", "ruleBefore": "", "duration": 0, "mainStateCode": 1, "mainStateName": "正常发电" },
  { "priority": 3, "rule": "Turstatus in (7)", "ruleBefore": "", "duration": 0, "mainStateCode": 2, "mainStateName": "限功率" },
  { "priority": 4, "rule": "Turstatus in (6,9)", "ruleBefore": "", "duration": 0, "mainStateCode": 3, "mainStateName": "待机" },
  { "priority": 5, "rule": "Turstatus in (11,12) ", "ruleBefore": "", "duration": 0, "mainStateCode": 4, "mainStateName": "维护" },
  { "priority": 6, "rule": "Turstatus in (1,3,4) ", "ruleBefore": "", "duration": 0, "mainStateCode": 5, "mainStateName": "停机" },
  { "priority": 7, "rule": "Turstatus in (2) ", "ruleBefore": "", "duration": 0, "mainStateCode": 6, "mainStateName": "故障" }
      ],
      input_points: "WindSpeed1@1m@AVG,Turstatus,ConGridsideVoltageL1L2@1m@MAX,ConGridsideVoltageL1L2@1m@MIN,WindSpeed1@1m@MAX,WindSpeed1@1m@MIN",
    },
    {
      label: "测试模板2",
      value: "2",
      pointName: "SState",
      formula: [
  { "priority": 0, "rule": "Turstatus in (8) || (ConGridsideVoltageL1L2@1m@MAX-ConGridsideVoltageL1L2@1m@MIN==0 && WindSpeed1@1m@MAX-WindSpeed1@1m@MIN==0)", "ruleBefore": "", "duration": 0, "subStateCode": 37, "subStateName": "通讯中断" },
  { "priority": 0, "rule": "WindSpeed1@1m@AVG == null", "ruleBefore": "", "duration": 0, "subStateCode": 37, "subStateName": "通讯中断" },
  { "priority": 10, "rule": "Turstatus in (5)", "ruleBefore": "", "duration": 0, "subStateCode": 1, "subStateName": "正常发电" },
  { "priority": 20, "rule": "Turstatus in (7)", "ruleBefore": "", "duration": 0, "subStateCode": 2, "subStateName": "电网限功率" },
  { "priority": 30, "rule": "Turstatus in (6,9) && AmbientTemp < -15", "ruleBefore": "", "duration": 0, "subStateCode": 8, "subStateName": "温度低待机" },
  { "priority": 30, "rule": "Turstatus in (6,9) && AmbientTemp > 35", "ruleBefore": "", "duration": 0, "subStateCode": 9, "subStateName": "温度高待机" },
  { "priority": 31, "rule": "Turstatus in (6,9) && WindSpeed1 > 20", "ruleBefore": "", "duration": 0, "subStateCode": 7, "subStateName": "大风切出" },
  { "priority": 31, "rule": "Turstatus in (6,9) && WindSpeed1 > 4 && WindSpeed1 < 20", "ruleBefore": "", "duration": 0, "subStateCode": 11, "subStateName": "异常待机" },
  { "priority": 32, "rule": "Turstatus in (6,9)", "ruleBefore": "", "duration": 0, "subStateCode": 6, "subStateName": "小风待机" },
  { "priority": 40, "rule": "", "ruleBefore": "'101' in signState", "duration": 0, "subStateCode": 12, "subStateName": "检测维护" },
  { "priority": 40, "rule": "", "ruleBefore": "'102' in signState", "duration": 0, "subStateCode": 13, "subStateName": "定检维护" },
  { "priority": 40, "rule": "", "ruleBefore": "'103' in signState", "duration": 0, "subStateCode": 14, "subStateName": "巡检维护" },
  { "priority": 40, "rule": "", "ruleBefore": "'104' in signState", "duration": 0, "subStateCode": 15, "subStateName": "缺陷维护" },
  { "priority": 40, "rule": "", "ruleBefore": "'105' in signState", "duration": 0, "subStateCode": 16, "subStateName": "技改维护" },
  { "priority": 40, "rule": "", "ruleBefore": "'106' in signState", "duration": 0, "subStateCode": 17, "subStateName": "预警维护" },
  { "priority": 40, "rule": "", "ruleBefore": "'107' in signState", "duration": 0, "subStateCode": 18, "subStateName": "覆冰" },
  { "priority": 40, "rule": "", "ruleBefore": "'108' in signState", "duration": 0, "subStateCode": 19, "subStateName": "台风" },
  { "priority": 40, "rule": "", "ruleBefore": "'109' in signState", "duration": 0, "subStateCode": 20, "subStateName": "地震" },
  { "priority": 40, "rule": "", "ruleBefore": "'110' in signState", "duration": 0, "subStateCode": 21, "subStateName": "民事原因" },
  { "priority": 40, "rule": "", "ruleBefore": "'111' in signState", "duration": 0, "subStateCode": 22, "subStateName": "新建风机接入" },
  { "priority": 40, "rule": "", "ruleBefore": "'112' in signState", "duration": 0, "subStateCode": 23, "subStateName": "扇区管理停机" },
  { "priority": 40, "rule": "WTUR_Bool_Rd_b1_LimPowStopState == 1", "ruleBefore": "'113' in signState ||", "duration": 0, "subStateCode": 24, "subStateName": "电网限功率停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'114' in signState", "duration": 0, "subStateCode": 25, "subStateName": "现货交易停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'116' in signState", "duration": 0, "subStateCode": 27, "subStateName": "电气检测停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'117' in signState", "duration": 0, "subStateCode": 28, "subStateName": "电气定检停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'118' in signState", "duration": 0, "subStateCode": 29, "subStateName": "电气巡检停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'119' in signState", "duration": 0, "subStateCode": 30, "subStateName": "电气缺陷停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'120' in signState", "duration": 0, "subStateCode": 31, "subStateName": "电气技改停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'121' in signState", "duration": 0, "subStateCode": 32, "subStateName": "电气故障停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'122' in signState", "duration": 0, "subStateCode": 33, "subStateName": "电网故障停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'123' in signState", "duration": 0, "subStateCode": 34, "subStateName": "电网检修停机" },
  { "priority": 40, "rule": "", "ruleBefore": "'124' in signState", "duration": 0, "subStateCode": 35, "subStateName": "故障检修" },
  { "priority": 50, "rule": "Turstatus in (1,3,4)", "ruleBefore": "", "duration": 0, "subStateCode": 26, "subStateName": "其他原因停机" },
  { "priority": 50, "rule": "Turstatus in (2)", "ruleBefore": "", "duration": 0, "subStateCode": 36, "subStateName": "故障停机" }
      ],
      input_points: "WindSpeed1@1m@AVG,Turstatus,AmbientTemp,WindSpeed1,WTUR_Bool_Rd_b1_LimPowStopState,ConGridsideVoltageL1L2@1m@MAX,ConGridsideVoltageL1L2@1m@MIN,WindSpeed1@1m@MAX,WindSpeed1@1m@MIN",
    },
  ],
}
